# Travis CI is only used to check the lesson and is not involved in its deployment
dist: bionic # python 3.6 included
language: ruby
rvm:
  - 2.7.2

branches:
  only:
  - gh-pages
  - /.*/

cache:
  apt: true
  bundler: true
  directories:
    - /home/travis/.rvm/
    - $HOME/.cache/pip

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    
before_install:
  - sudo add-apt-repository -y "ppa:marutter/rrutter4.0"
  - sudo add-apt-repository -y "ppa:c2d4u.team/c2d4u4.0+"
  - sudo add-apt-repository -y "ppa:ubuntugis/ppa"
  - sudo add-apt-repository -y "ppa:cran/travis"
  - travis_apt_get_update
  - sudo apt-get install -y --no-install-recommends build-essential gcc g++ libblas-dev liblapack-dev libncurses5-dev libreadline-dev libjpeg-dev libpcre3-dev libpng-dev zlib1g-dev libbz2-dev liblzma-dev libicu-dev cdbs qpdf texinfo libssh2-1-dev gfortran jq python3-pip r-base
  - curl -fLo /tmp/texlive.tar.gz https://github.com/jimhester/ubuntu-bin/releases/download/latest/texlive.tar.gz
  - tar xzf /tmp/texlive.tar.gz -C ~
  - export PATH=${TRAVIS_HOME}/texlive/bin/x86_64-linux:$PATH
  - tlmgr update --self
  - curl -fLo /tmp/pandoc-2.2-1-amd64.deb https://github.com/jgm/pandoc/releases/download/2.2/pandoc-2.2-1-amd64.deb
  - sudo dpkg -i /tmp/pandoc-2.2-1-amd64.deb
  - sudo apt-get install -f
  - rm /tmp/pandoc-2.2-1-amd64.deb
  ## Install python and dependencies
  - python3 -m pip install --upgrade pip setuptools wheel
  - python3 -m pip install pyyaml
  - gem update --system
  - gem --version
  - gem install bundler
  - gem update bundler

script:
  - make site
  - make lesson-check-all
  - make --always-make site
